[package]
name = "cafecoder-rs"
version = "0.1.0"
authors = ["earlgray <earlgray283@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sqlx = { version = "0.5.1", features = [ "runtime-tokio-rustls", "mysql", "macros", "chrono" ] }
dotenv = "0.15.0"
chrono = "0.4"
bollard = "0.9"
rand = "0.8.0"
tokio = { version = "1.8.4", features = [ "full" ] }
hyper = "0.14"
anyhow = "1.0.37"
async-trait = "0.1.42"
futures = "0.3.12"
